BusinessLMSWeb/Controllers/FollowupsController.cs
using BusinessLMS.Models;
using BusinessLMSWeb.Filters;
using BusinessLMSWeb.Helpers;
using BusinessLMSWeb.ModelsView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BusinessLMSWeb.Controllers
{
	[Authorize]
	public class FollowupsController : BaseWebController
	{
		private List<Contact> _contacts
		{
			get { return Cookies.contactsCookie.GetContacts(); }
			set { if (value != null) Cookies.contactsCookie.SetContacts(value); else Cookies.contactsCookie.Nullify(); }
		}

		public ActionResult Index()
		{
			/* Get Clients For Autocomplete */
			_contacts = null;
			_contacts = GetContacts();
			List<FollowupView> followups = IBOVirtualAPI.GetIBOFollowupView(ibo.IBONum);
			return View(followups);
		}

		[IsNotPageRefresh]
		public ActionResult NewFollowup()
		{
			ContactFollowup model = new ContactFollowup();
			model.IBONum = ibo.IBONum;
			model.completed = false;
			model.datetime = System.DateTime.Now;
			return PartialView(model);
		}

		[IsNotPageRefresh]
		public ActionResult NewFollowupDate(DateTime date)
		{
			ContactFollowup model = new ContactFollowup();
			model.IBONum = ibo.IBONum;
			model.completed = false;
			model.datetime = System.DateTime.Now;
			model.datetime = date;
			return PartialView("NewFollowup", model);
		}

		[HttpPost]
		[IsNotPageRefresh]
		public ActionResult NewFollowupAjax(ContactFollowup model)
		{
			if (ModelState.IsValid == true && (model.contactId != 0))
			{
				bool result = IBOVirtualAPI.Create<ContactFollowup>(model);
				if (result)
				{
					return Json(new { success = true });
				}
				else
				{
					return Json(new { success = false, message = "There Was an issue saving the Followup, please try again. " });
				}
			}
			else
			{
				return Json(new { success = false, message = "Selecting a Contact is required" });
			}
		}

		[IsNotPageRefresh]
		public ActionResult EditFollowup(int id)
		{
			ContactFollowup followup = IBOVirtualAPI.Get<ContactFollowup>(id.ToString());
			Contact contact = IBOVirtualAPI.Get<Contact>(followup.contactId.ToString());
			ViewBag.contactName = contact.GetFullName();
			return PartialView(followup);
		}

		[HttpPost]
		[IsNotPageRefresh]
		public ActionResult EditFollowupAjax(ContactFollowup model)
		{
			if (ModelState.IsValid == true)
			{
				string result = IBOVirtualAPI.Update<ContactFollowup>(model.followupId.ToString(), model);
				return Json(new { success = true });
			}
			else
			{
				return Json(new { success = false });
			}
		}

		[HttpPost]
		[IsNotPageRefresh]
		public ActionResult DeleteFollowupAjax(int id)
		{
			try
			{
				string result = IBOVirtualAPI.Delete<ContactFollowup>(id.ToString());
				return Json(new { success = true });
			}
			catch
			{
				return Json(new { success = false });
			}
		}

		[HttpGet]
		[IsNotPageRefresh]
		public ActionResult Details(int id)
		{
			ContactFollowup followup = IBOVirtualAPI.Get<ContactFollowup>(id.ToString());
			Contact contact = IBOVirtualAPI.Get<Contact>(followup.contactId.ToString());
			ViewBag.contactName = contact.GetFullName();
			return PartialView(followup);
		}

		[HttpGet]
		[IsNotPageRefresh]
		public ActionResult SearchContact(string term)
		{
			if (_contacts == null) _contacts = GetContacts();
			List<SearchObject> userNames = (from cnt in _contacts
											where cnt.firstName.ToUpper().Contains(term.ToUpper()) || cnt.lastName.ToUpper().Contains(term.ToUpper())
											select new SearchObject { label = cnt.GetFullName(), value = cnt.contactId.ToString() }).ToList();
			return Json(userNames, JsonRequestBehavior.AllowGet);
		}

		private List<Contact> GetContacts()
		{
			List<Contact> contacts = IBOVirtualAPI.GetIBOContacts(ibo.IBONum);
			return contacts;
		}

		[IsNotPageRefresh]
		public ActionResult _HelpInfo()
		{
			return PartialView();
		}

		public ActionResult CompletFollowup (int id)
		{
			try
			{
				ContactFollowup followup = IBOVirtualAPI.Get<ContactFollowup>(id.ToString());
				followup.completed = true;
				string result = IBOVirtualAPI.Update<ContactFollowup>(followup.followupId.ToString(), followup);
				return Json(new { success = true });
			}
			catch
			{
				return Json(new { success = false });
			}
		}
	}
}

BusinessLMSWeb/Views/Followups/Details.cshtml
@model BusinessLMS.Models.ContactFollowup
<div class="metro">
	<div class="metro-container-300">
		<div class="metro-form-control p10">
			@TextResources.Businesslms.contactId
			<div class="metro-text-box">
				@ViewBag.contactName
			</div>
		</div>
		<div class="metro-form-control p10">
			@Html.LabelFor(model => model.method)
			<div class="metro-text-box">
				@Html.DisplayTextFor(model => model.method)
			</div>
		</div>
		<div class="metro-form-control p10">
			@Html.LabelFor(model => model.datetime) (mm/dd/yyyy)
			<div class="metro-text-box">
				@Html.DisplayTextFor(model => model.datetime)
			</div>
		</div>	
	</div>
</div>

BusinessLMSWeb/Views/Followups/EditFollowup.cshtml
@model BusinessLMS.Models.ContactFollowup
<div class="metro-container-300">
@using (Html.BeginForm("EditFollowupAjax", "Followups", FormMethod.Post, new { @class = "metro-form", id = "current_form" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend></legend>
        <div class="metro-form-control">
            @TextResources.Businesslms.contactId
            <div class="metro-text-box">
                <input type="text" name="contactName" id="contactName" value="@ViewBag.contactName" />
                @Html.ValidationMessageFor(model => model.contactId)
            </div>
        </div>
        <div class="metro-form-control">
            @Html.LabelFor(model => model.method)
            <div class="metro-text-box">
                @Html.EditorFor(model => model.method)
                @Html.ValidationMessageFor(model => model.method)
            </div>
        </div>
        <div class="metro-form-control">
            @Html.LabelFor(model => model.datetime) (mm/dd/yyyy)
            <div class="metro-text-box">
                @Html.EditorFor(model => model.datetime)
                @Html.ValidationMessageFor(model => model.datetime)
            </div>
            <div class="metro-text-date"><img src="~/Images/Date.png" /></div>
        </div>
        @Html.HiddenFor(model => model.contactId)
        @Html.HiddenFor(model => model.IBONum)
        @Html.HiddenFor(model => model.completed)
        <div class="metro-align-right">
            <input type="button" value="@TextResources.Businesslms.Cancel" class="metro-button" onclick="CancelContact();" />
            <input type="button" value="@TextResources.Businesslms.Update" class="metro-button" onclick="submitform(this.form);" />
        </div>
    </fieldset>
}
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#current_form");
        $(".date-picker").datepicker({
            yearRange: "-90:+0",
            changeMonth: true,
            changeYear: true
        });
    });
</script>

BusinessLMSWeb/Views/Followups/Index.cshtml
@model IEnumerable<BusinessLMSWeb.ModelsView.FollowupView>
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="metro-info-icons">
	<a href="#" class="help-link help-link-action" title="Help">Help</a>
</div>
<div class="title" style="margin-bottom:40px;">
	<h2>@TextResources.Businesslms.Index.</h2>
</div>
<div class="metro-container-990">
	<table id="data-table">
		<thead>
			<tr>
				<th>@Html.DisplayNameFor(model => model.ContactName)</th>
				<th>@Html.DisplayNameFor(model => model.Method)</th>
				<th>@Html.DisplayNameFor(model => model.datetime)</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		@foreach (var item in Model) {
			<tr>
				<td>@Html.DisplayFor(modelItem => item.ContactName)</td>
				<td>@Html.DisplayFor(modelItem => item.Method)</td>
				<td>@Html.DisplayFor(modelItem => item.datetime)</td>
				<td>
					@Html.ActionLink("Done", "CompletFollowup", new { id=item.followupId }, new { @class = "completedlink", title = "Complet Followup", id=item.followupId } )
					<a href="javascript:EditItem(@(item.followupId));" class = "edit-link-sm-black editlink">Edit</a>
					@Html.ActionLink("Delete", "DeleteFollowupAjax", new { id=item.followupId }, 
						new { @class = "del-link-sm-black deletelink", title = "Delete Followup" })
				</td>
			</tr>
		}
		</tbody>
	</table>
	<div class="metro-align-right">
		<input type="button" value="@TextResources.Businesslms.AddNew" class="metro-button" onclick="AddNewItem();" />
	</div>
</div>
<div id="followupInfo"></div>
<div id="modalWindow"></div>
<div id="delete-dialog" title="Confirmation">
	<p>@TextResources.Businesslms.DeleteText @TextResources.Businesslms.followupId?</p>
</div>
<div id="completed-dialog" title="Confirmation">
	<p>@TextResources.Businesslms.CompletedText @TextResources.Businesslms.followupId?</p>
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/Scripts/Followups/Index.js")
}

BusinessLMSWeb/Views/Followups/NewFollowup.cshtml
@model BusinessLMS.Models.ContactFollowup
<div class="metro">
<div class="metro-container-300">
@using (Html.BeginForm("NewFollowupAjax", "Followups", FormMethod.Post, new { @class = "metro-form", id = "current_form" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend></legend>
        <div class="metro-form-control">
            @TextResources.Businesslms.contactId
            <div class="metro-text-box">
                <input type="text" name="contactName" id="contactName" value="" />
                @Html.ValidationMessageFor(model => model.contactId)
            </div>
        </div>
        <div class="metro-form-control">
            @Html.LabelFor(model => model.method)
            <div class="metro-text-box">
                @Html.EditorFor(model => model.method)
                @Html.ValidationMessageFor(model => model.method)
            </div>
        </div>
        <div class="metro-form-control">
            @Html.LabelFor(model => model.datetime) (mm/dd/yyyy)
            <div class="metro-text-box">
                @Html.EditorFor(model => model.datetime)
                @Html.ValidationMessageFor(model => model.datetime)
            </div>
            <div class="metro-text-date"><img src="~/Images/Date.png" /></div>
        </div>
        @Html.HiddenFor(model => model.contactId)
        @Html.HiddenFor(model => model.IBONum)
        @Html.HiddenFor(model => model.completed)
        <div class="metro-align-right">
            <input type="button" value="@TextResources.Businesslms.Cancel" class="metro-button" onclick="CancelItem();" />
            <input type="button" value="@TextResources.Businesslms.Create" class="metro-button" onclick="submitform(this.form);" />
        </div>
    </fieldset>
}
</div></div>
<script type="text/javascript">
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#current_form");
        $(".date-picker").datepicker({
            yearRange: "-90:+0",
            changeMonth: true,
            changeYear: true
        });
        $("#contactName").autocomplete({
        	source: "/Followups/SearchContact/",
        	open: function () {
        		$(this).autocomplete('widget').css('z-index', 1111);
        		return false;
        	},
        	select: function (event, ui) {
        		$("#contactName").val(ui.item.label);
        		$("#contactId").val(ui.item.value);
        		return false;
        	}
        });
    });
</script>

BusinessLMSWeb/Views/Followups/_HelpInfo.cshtml
<div id="info-modal" title="Contact Followup" style="width:770px;height:550px;resize:none">
</div>