BusinessLMSWeb/Models/IBO.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BusinessLMS.Models
{
	public partial class IBO
	{
		[Required]
		[Display(Name = "IBONum", ResourceType = typeof(TextResources.Businesslms))]
		public string IBONum { get; set; }

		[Display(Name = "UpLine", ResourceType = typeof(TextResources.Businesslms))]
		public string UPLine { get; set; }

		[Required]
		[Display(Name = "languageId", ResourceType = typeof(TextResources.Businesslms))]
		public int languageId { get; set; }

		[Required]
		[Display(Name = "firstName", ResourceType = typeof(TextResources.Businesslms))]
		public string firstName { get; set; }

		[Required]
		[Display(Name = "lastName", ResourceType = typeof(TextResources.Businesslms))]
		public string lastName { get; set; }

		public string accesstoken { get; set; }

		[Required]
		[Display(Name = "email", ResourceType = typeof(TextResources.Businesslms))]
		public string email { get; set; }

		[Display(Name = "facebookid", ResourceType = typeof(TextResources.Businesslms))]
		public string facebookid { get; set; }

		[Display(Name = "twitter", ResourceType = typeof(TextResources.Businesslms))]
		public string twitter { get; set; }

		public System.DateTime datetime { get; set; }

		[Display(Name = "picture", ResourceType = typeof(TextResources.Businesslms))]
		public string picture { get; set; }

		public int UserId { get; set; }

		[Required]
		[Display(Name = "birthday", ResourceType = typeof(TextResources.Businesslms))]
		public Nullable<System.DateTime> birthday { get; set; }

		[Display(Name = "phone", ResourceType = typeof(TextResources.Businesslms))]
		public string phone { get; set; }

		[Display(Name = "level", ResourceType = typeof(TextResources.Businesslms))]
		public int level { get; set; }

		[Required]
		[Display(Name = "newsletteroptin", ResourceType = typeof(TextResources.Businesslms))]
		public bool newsletteroptin { get; set; }

		[Required]
		[Display(Name = "terms", ResourceType = typeof(TextResources.Businesslms))]
		public bool terms { get; set; }

	}
}

BusinessLMSWeb/Controllers/IBOController.cs
using BusinessLMS.Models;
using BusinessLMSWeb.Helpers;
using System;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace BusinessLMSWeb.Controllers
{
	[Authorize]
	public class IBOController : BaseWebController
	{
		private SelectList languages
		{
			get
			{
				return new SelectList(IBOVirtualAPI.GetLanguages(), "languageId", "language1");
			}
		}

		public ActionResult AddIBO()
		{
			ViewBag.languages = languages;
			return View();
		}

		[HttpPost]
		public ActionResult AddIBO(IBO model)
		{
			ViewBag.languages = languages;
			IBO ibo = ModelParser.ParseIBO(model);
			ibo.UserId = WebSecurity.CurrentUserId;
			ibo.datetime = DateTime.Now;
			ibo.facebookid = FacebookId != null ? FacebookId : "";
			ibo.accesstoken = AccessToken != null ? AccessToken : "";
			ibo.level = model.level;
			try
			{
				bool result = IBOVirtualAPI.Create<IBO>(ibo);
				Cookies.iboCookie.Nullify();
				return RedirectToAction("Index", "Dashboard");
			}
			catch
			{
				ModelState.AddModelError(null, "The IBO Number is already been used");
				return View(model);
			}
		}

		public ActionResult Update()
		{
			IBO ibo = IBOVirtualAPI.GetIBOByUId(WebSecurity.CurrentUserId.ToString());
			ViewBag.languages = languages;
			return View(ibo);
		}

		[HttpPost]
		public ActionResult Update(IBO model)
		{
			IBO iboUpdate = ModelParser.ParseIBO(model);
			iboUpdate.UserId = WebSecurity.CurrentUserId;
			iboUpdate.datetime = DateTime.Now;
			iboUpdate.facebookid = FacebookId != null ? FacebookId : "";
			iboUpdate.accesstoken = AccessToken != null ? AccessToken : "";
			iboUpdate.level = model.level;
			try
			{
				string result = IBOVirtualAPI.Update<IBO>(model.IBONum, iboUpdate);
				Cookies.Nullify();
			}
			catch { }
			return RedirectToAction("Index", "Dashboard");
		}
	}
}

BusinessLMSWeb/Views/IBO/AddIBO.cshtml
@model BusinessLMS.Models.IBO
@using BusinessLMSWeb.Helpers
@{
	ViewBag.Title = "IBO Details";
	Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}
<div class="metro-container-300">
	<div class="title" style="margin-bottom: 40px;">
		<h2>@TextResources.Businesslms.IBODetails.</h2>
	</div>
	@using (Html.BeginForm("AddIBO", "IBO", FormMethod.Post, new { @class = "metro-form", id = "createIBOForm" }))
 {
		@Html.ValidationSummary(true)
		<fieldset>
			<legend></legend>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.IBONum)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.IBONum)
					@Html.ValidationMessageFor(model => model.IBONum)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.firstName)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.firstName)
					@Html.ValidationMessageFor(model => model.firstName)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.lastName)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.lastName)
					@Html.ValidationMessageFor(model => model.lastName)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.languageId)
				<div class="metro-select-box">
					@Html.DropDownListFor(model => model.languageId, (SelectList)ViewBag.languages)
					@Html.ValidationMessageFor(model => model.languageId)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.email)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.email)
					@Html.ValidationMessageFor(model => model.email)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.phone)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.phone)
					@Html.ValidationMessageFor(model => model.phone)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.birthday)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.birthday)
					@Html.ValidationMessageFor(model => model.birthday)
				</div>
				<div class="metro-text-date">
					<img src="~/Images/Date.png" />
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.level)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.level)
					@Html.ValidationMessageFor(model => model.level)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.twitter)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.twitter)
					@Html.ValidationMessageFor(model => model.twitter)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.UPLine)
				<div id="divIboName" class="metro-form-control">
					<input type="text" class="metro-text-box" name="iboName" id="iboName" /></div>
				<div id="divLoading"></div>
			</div>
			<div class="metro-form-control">
				@Html.CheckBoxMetroFor(model => model.newsletteroptin, new { @class = "metro-check" })
			</div>
			<div class="metro-form-control">
				@Html.CheckBoxMetroFor(model => model.terms, new { @class = "metro-check" }) @Html.ActionLink(TextResources.Businesslms.terms, "Terms", "Home")
			</div>
			@Html.HiddenFor(model => model.picture)
			@Html.HiddenFor(model => model.UPLine)
		</fieldset>
 }
	@TextResources.Businesslms.IBOpicture
	<form action="/api/Files" method="post" enctype="multipart/form-data" id="file_upload">
		<div id="filediv">
			<input type="file" name="file" />
			<div id="status"></div>
		</div>
		<input type="submit" value="@TextResources.Businesslms.Upload" id="btnUpload" class="metro-button" />
	</form>

	<a href="#" class="metro-button photoSelect ">Select photo from Facebook</a>

	<div class="metro-align-right">
		<input type="button" value="@TextResources.Businesslms.Save" class="metro-button" onclick="submitform();" />
	</div>
	<div class="metro-align-right" style="margin-top: 20px;">
		@TextResources.Businesslms.GoBack
		@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
  {
			@Html.AntiForgeryToken()
			<a href="javascript:document.getElementById('logoutForm').submit()">@TextResources.BusinesslmsHome.MenuHome</a>
  }
	</div>
</div>

@{ Html.RenderPartial("CSPhotoSelector");}

<script type="text/javascript">
	window.fbAsyncInit = function () {
		FB.init({ appId: facebookAppId, cookie: true, status: true, xfbml: true, oauth: true });
	};
	(function (d) {
		var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
		if (d.getElementById(id)) { return; }
		js = d.createElement('script'); js.id = id; js.async = true;
		js.src = "//connect.facebook.net/en_US/all.js";
		ref.parentNode.insertBefore(js, ref);
	}(document));
</script>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/jqueryupload")
	@Scripts.Render("~/Scripts/IBO/AddIBO.js")
	@Scripts.Render("~/Scripts/Shared/csphotoselector.js")
}

BusinessLMSWeb/Views/IBO/Update.cshtml
@model BusinessLMS.Models.IBO
@using BusinessLMSWeb.Helpers
@{
	ViewBag.Title = "IBO Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="metro-container-300">
	<div class="title" style="margin-bottom:40px;">
		<h2>@TextResources.Businesslms.IBODetails.</h2>
	</div>
	@using (Html.BeginForm("Update","IBO", FormMethod.Post, new { @class = "metro-form", id = "createIBOForm" })) {
		@Html.ValidationSummary(true)
		<fieldset>
			<legend></legend>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.IBONum)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.IBONum)
					@Html.ValidationMessageFor(model => model.IBONum)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.firstName)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.firstName)
					@Html.ValidationMessageFor(model => model.firstName)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.lastName)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.lastName)
					@Html.ValidationMessageFor(model => model.lastName)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.languageId)
				<div class="metro-select-box">
					@Html.DropDownListFor(model => model.languageId, (SelectList)ViewBag.languages)
					@Html.ValidationMessageFor(model => model.languageId)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.email)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.email)
					@Html.ValidationMessageFor(model => model.email)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.phone)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.phone)
					@Html.ValidationMessageFor(model => model.phone)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.birthday)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.birthday)
					@Html.ValidationMessageFor(model => model.birthday)
				</div>
				<div class="metro-text-date"><img src="~/Images/Date.png" /></div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.level)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.level)
					@Html.ValidationMessageFor(model => model.level)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.twitter)
				<div class="metro-text-box">
					@Html.EditorFor(model => model.twitter)
					@Html.ValidationMessageFor(model => model.twitter)
				</div>
			</div>
			<div class="metro-form-control">
				@Html.LabelFor(model => model.UPLine)
				<div id="divIboName" class="metro-form-control">
					<input type="text" class="metro-text-box" name="iboName" id="iboName" value="@Model.UPLine" /></div>
				<div id="divLoading"></div>
			</div>

			<div class="metro-form-control">
				@Html.CheckBoxMetroFor(model => model.newsletteroptin, new { @class = "metro-check" })
			</div>
			@Html.HiddenFor(model => model.picture)
			@Html.HiddenFor(model => model.UPLine)
		</fieldset>
	}
	@TextResources.Businesslms.IBOpicture
	<form action="/api/Files" method="post" enctype="multipart/form-data" id="file_upload" >
		<div id = "filediv">
			<input type="file" name="file"/>
			<div id="status"></div>
		</div>
		<input type="submit" value="@TextResources.Businesslms.Upload" id="btnUpload" class="metro-button" />
        <a href="#" class="metro-button photoSelect ">Select photo from Facebook</a>
	</form>
	<div class="metro-align-right">
		<input type="button" value="@TextResources.Businesslms.Update" class="metro-button" onclick="submitform();" />
	</div>
	<div class="metro-form-control">
		@Html.ActionLink(TextResources.Businesslms.terms, "Terms","Home")
	</div>
</div>

@{ Html.RenderPartial("CSPhotoSelector");}

<script type="text/javascript">
    window.fbAsyncInit = function () {
        FB.init({ appId: facebookAppId, cookie: true, status: true, xfbml: true, oauth: true });
    };
    (function (d) {
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) { return; }
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));
</script>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/jqueryupload")
	@Scripts.Render("~/Scripts/IBO/AddIBO.js")
	@Scripts.Render("~/Scripts/Shared/_layout.js")
    @Scripts.Render("~/Scripts/Shared/csphotoselector.js")
}